FROM mambaorg/micromamba:latest

LABEL base.image="mambaorg/micromamba:latest"
LABEL dockerfile.version="1"
LABEL software="genelab-utils"
LABEL software.version="1.3.22"
LABEL description="GeneLab Illumina amplicon sequencing data processing pipeline (AmpIllumina)"
LABEL website="https://github.com/nasa/GeneLab_Data_Processing/tree/master/Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A"
LABEL license="NASA OPNE SOURCE v1.3"
LABEL maintainer="Chienchi Lo"
LABEL maintainer.email="chienchi@lanl.gov"

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV SHELL=/bin/bash
ENV LC_ALL=C
# SHELL ["/bin/bash", "-c"] 
#USER root 

#  genelab-utils install 
RUN micromamba create -n genelab-utils -c conda-forge -c bioconda -c defaults -c astrobiomike 'genelab-utils>=1.1.02' jq \
    && micromamba clean --all -y \
    && echo "micromamba activate genelab-utils" >> ~/.bashrc \
    && echo "alias ll='ls -alh' " >> ~/.bashrc

ENV PATH="${PATH}:/opt/conda/envs/genelab-utils/bin"

WORKDIR /data

# Download the workflow template files
RUN eval "$(micromamba shell hook --shell bash)" \ 
    && conda config --add channels conda-forge \
    && conda config --set channel_priority strict \
    && micromamba activate genelab-utils \
    && GL-get-workflow Amplicon-Illumina --wanted-version 1.0.1

# directory with Snakefile  
WORKDIR /data/SW_AmpIllumina-A_1.0.1

